### ISSUE TITLE
Cross check Dingo and bilby likelihoods

### ISSUE THREAD

**Issue by max-dax** [dingo-gw/dingo#132]
We observe small deviations between Dingo and published bilby results. This happens even when the Dingo-IS sample efficiency is large. One possible explanation is that we use a different likelihood (e.g., missing a window factor somewhere). We should therefore check that the Dingo likelihood agrees with bilby likelihoods.

Ways to track this down:

- Take some bilby samples (these include their likelihoods), insert them into a Dingo results file (make sure to provide the appropriate strains, PSDs, domain settings, ...) and run importance sampling with Dingo. Check that the bilby likelihoods match those inferred with Dingo. I did this with GW150914 and the published bilby results, for which we see deviations of O(1), which could be due to calibration marginalization. We should check that we get exact matches when bilby does not apply calibration marginalization.
- Run `bilby_pipe` for an event for which we have dingo samples. Step through the likelihood calculation with the pycharm debugger (or a similar tool). Check that (a) the data is identical to what Dingo uses (e.g., make sure that the PSD is not off by a window factor, the conventions are not always consistent) and (b) that the computed waveforms are identical to Dingo.

There is also this script https://github.com/dingo-gw/dingo-devel/blob/main/misc_scripts/run_bilby.py to run Dingo from a yaml file.

**Comment by nihargupte-ph** [comment]
Fixed with https://github.com/dingo-gw/dingo/pull/180. Finally!
