### ISSUE TITLE
15D flow doesn't allow for batch size specification

### ISSUE THREAD

**Issue by nihargupte-ph** [dingo-gw/dingo#168]
For the most part we use the 2D flow for density estimation. However, sometimes it is useful to use the 15D flow either for debugging (or temporaily) for 1 detector networks. However, we can't specify the batch_size when sampling. This can be fixed by editing https://github.com/dingo-gw/dingo/blob/main/dingo/gw/importance_sampling/importance_weights.py#L121 to provide settings["batch_size"].

**Comment by stephengreen** [comment]
Feel free to edit this script. It's somewhat deprecated compared to dingo_pipe. In addition, dingo_pipe should be updated to allow for 14D or 15D density recovery.
