### ISSUE TITLE
Calling SciPy windows after v=1.13.0

### ISSUE THREAD

**Issue by JonathanMushkin** [dingo-gw/dingo#247]
Starting with scipy 1.13.0, 
scipy.signal.tukey
is deprecated, and should be accessed through 
scipy.signal.windows.tukey
this should be backward compatible with older scipy versions. Applying this change in dingo will allow using newer scipy versions.
https://scipy.github.io/devdocs/release/1.13.0-notes.html#expired-deprecations

**Comment by stephengreen** [comment]
This should be fixed in the most recent release, dingo-gw v0.5.11: https://github.com/dingo-gw/dingo/releases/tag/v0.5.11

I did a search and I didn't find any other deprecated imports, am I missing something?

**Comment by wittscien** [comment]
There is still a line
`from scipy.signal import tukey`
in gwutils.py.

Maybe also fix this?
