### ISSUE TITLE
git hash to model settings

### ISSUE THREAD

**Issue by max-dax** [dingo-gw/dingo#42]
It could be handy to add an option for saving the git hash to the model settings.

In a terminal, one can simply get the code by `git rev-parse HEAD`, within python one can use `gitpython` https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script.

**Comment by stephengreen** [comment]
We now save the Dingo version in all the output files. This includes the git hash if not using a tagged version. However, it does require a reinstall to update the version. Should we consider this issue closed?

**Comment by max-dax** [comment]
I think this is fine. When people update from PyPI this will automatically happen, and this is our main use case.
