### ISSUE TITLE
Clean up output of train scripts

### ISSUE THREAD

**Issue by max-dax** [dingo-gw/dingo#46]
The print output of the train script is currently extremely long. When first building the model, it prints >300 lines (see comment below). 

- Some of this is from testing the reduced basis and should be fixed with issue #45. 
- There are hundreds of lines of model settings. I feel that they should not all be printed. Instead we could maybe print the most important settings only (just a couple of lines), and then a statement along the lines of `for more information run dingo_info model.pt`. This would require the implementation of `dingo_info`, which for a model should be pretty straightforward. (In general, this function should also work for datasets later). 
- Currently I believe the loss is printed in each iteration. We should set a more sensible default, such as 10 prints per epoch.

We could also think about adding a `--verbose` flag. If this is set, the train script should automatically print the `dingo_info` stuff after initialisation of the model, and the loss would be printed in each iteration (the latter would e.g. help with the analysis of loading times of the data loader).

**Comment by stephengreen** [comment]
Replaced by #152
